### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Xvnc': 'Xvnc'

### ISSUE THREAD

**Issue by davidyu513** [ponty/PyVirtualDisplay#88]
I have installed tigervnc in Mac but when I ran python3 -m pyvirtualdisplay.examples.vncserver I am getting 
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyvirtualdisplay/examples/vncserver.py", line 7, in <module>
    with Display(backend="xvnc", size=(100, 60), rfbport=5904) as disp:
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyvirtualdisplay/display.py", line 63, in __init__
    **kwargs
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyvirtualdisplay/xvnc.py", line 46, in __init__
    manage_global_env=manage_global_env,
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyvirtualdisplay/abstractdisplay.py", line 85, in __init__
    helptext = get_helptext(program)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyvirtualdisplay/util.py", line 17, in get_helptext
    shell=False,
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Xvnc': 'Xvnc'

Can someone point me to a right direction?

**Comment by ponty** [comment]
On Ubuntu Linux symlinks are created for Xvnc:

/usr/bin/Xvnc -> /etc/alternatives/Xvnc*
/etc/alternatives/Xvnc -> /usr/bin/Xtigervnc*

You can do the same.
Can you start Xtigervnc in console?
I can rename Xvnc to Xtigervnc in the next version.

**Comment by davidyu513** [comment]
Thanks for the reply, I used `brew install tiger-vnc` to install TigerVnc for Mac but I don't see Xvnc or Xtigervnc in /usr/bin/ or  /opt/homebrew/bin. Trying to run Xvnc or Xtigervnc as you suggested returns command not found. However I am able to run TigerVNC by running `vncviewer` command. I guess I can try to symlink vncviewer to Xvnc and see

**Comment by The-Compiler** [comment]
A VNC viewer and a VNC server are two different pieces of software.

**Comment by ponty** [comment]
Please check if Xvnc is installed on Mac. 

Xvnc is Linux specific according to the README:
https://github.com/TigerVNC/tigervnc

```
Unix/Linux-Specific (not Mac)

The Unix/Linux version of TigerVNC contains the following programs:

    Xvnc - the TigerVNC Server for Unix. Xvnc is both a VNC server and an X
        server with a "virtual" framebuffer. You should normally use the vncserver service to start Xvnc.
```
